name: Deploy to S3 and Invalidate CloudFront
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github 에 빌드한 파일 불러오기
        uses: actions/checkout@v4
