name: Github Actions Prac01
on:
  push:
    branches:
      - main

jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest

    steps:
      - name: hello world
        run: echo "Hello Wolrd!"

      - name: 여러 명령어 문자 작성하기
        run: |
          echo "Good"
          echo "Hi"
          pwd
